{% set name = "mutagen" %}
{% set version = "1.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 719fadef0a978c31b4cf3c956261b3c58b6948b32023078a2117b1de09f0fc99

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

  commands:
    - mid3cp -h
    - mid3iconv -h
    - moggsplit -h
    - mutagen-inspect -h
    - mutagen-pony -h
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quodlibet/mutagen
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Read and write audio tags for many formats
  dev_url: https://github.com/quodlibet/mutagen
  doc_url: https://mutagen.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
