{% set name = "mutagen" %}
{% set version = "1.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e5f8ba84836b99fe60be5fb27f84be4ad919bbb6b49caa6ae81e70584b55e58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

  commands:
    - mid3cp -h
    - mid3iconv -h
    - moggsplit -h
    - mutagen-inspect -h
    - mutagen-pony -h
    - pip check

  requires:
    - pip

about:
  home: https://github.com/quodlibet/mutagen
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Read and write audio tags for many formats
  dev_url: https://github.com/quodlibet/mutagen
  doc_url: https://mutagen.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
