{% set name = "mutagen" %}
{% set version = "1.45.1" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "6397602efb3c2d7baebd2166ed85731ae1c1d475abca22090b7141ff5034b3e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  preserve_egg_dir: true
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

  commands:
    - mid3cp -h
    - mid3iconv -h
    - moggsplit -h
    - mutagen-inspect -h
    - mutagen-pony -h

about:
  home: https://github.com/quodlibet/mutagen
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: Read and write audio tags for many formats
  dev_url: https://github.com/quodlibet/mutagen
  doc_url: https://mutagen.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
